### ISSUE TITLE
Please Update

### ISSUE THREAD

**Issue by longshen2020** [MCQTSS/MCQTSS_4399register#1]
好像不能使用了

**Comment by MCQTSS** [comment]
可以的，我服务器每天还在自动注册，可以发一下错误日志看看，如果和ddddocr有关可以尝试删除这部分代码或百度查找解决方法

**Comment by longshen2020** [comment]
我不知道为什么 我运行时没有差运行库 但是什么信息都没有返回 过了等待时间后就开始休眠 只有        print('开始休眠12秒后继续发起')发出了放回
